version: '3'
services:
  front:
    image: node:16-alpine
    working_dir: /usr/app
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./$WORKDIR:/usr/app
    ports:
      - "3000:3000"
  scss:
    build: .
    working_dir: /var/www/js/scss
    volumes:
      - ./$WORKDIR/public:/var/www/js
    stdin_open: true
    tty: true