version: '3'
volumes:
  node_modules_volume:
services:
  front:
    image: node:16-alpine
    working_dir: /usr/app
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./$WORKDIR:/usr/app
      - node_modules_volume:/usr/app/node_modules
    ports:
      - "3000:3000"